.TH GAMEPLAYFOOTBALL 6 "July 02 , 2021"
.SH NAME
gameplayfootball \- Manual for gameplayfootball
.SH SYNOPSIS
.B gameplayfootball
[path]
.SH DESCRIPTION
.PP
This command (
.B gameplayfootball
) only takes one optional parameter.
.SH OPTIONS
Options that may be passed to the game:
.TP
\fBpath\fR
, path to configuration file (defaults to $HOME/.football.config)
.br
.SH AUTHOR
This game is based on a fork of discontinued GameplayFootball written by Bastiaan Konings Schuiling - Properly Decent.
.PP
This manual page was written by Jhonny Oliveira <jhonny.oliveira@gmail.com> for the XtraDeb project (but may be used by others). Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 any later version published by the Free Software Foundation.
.PP
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL-2.
